- name: 2.5 Reducing the attack perimeter of the Linux kernel
  hosts: all
  become: true
  become_method: sudo
  remote_user: elmed_ave
  tasks:
    - name: Applying sysctl change
      command: sysctl -p
